In [25]:
import numpy as np
from numpy.random import rand

In [26]:
X=np.array(([0.9,0.8],[0.6,0.3],[0.9,0.1],[0.9,0.8]))
Y=np.array(([0],[1],[1],[0]))

In [27]:
X

array([[0.9, 0.8],
       [0.6, 0.3],
       [0.9, 0.1],
       [0.9, 0.8]])

In [41]:
def sigmoid(z):
  return 1/(1+np.exp(-z))


class NeuralNetwork:
  def __init__(self,x,y,nodes_in_layer1=4,nodes_in_layer2=3,nodes_in_layer3=1):

    self.inputs_in_layer0=x
    self.y=y

    self.nodes_in_layer1=nodes_in_layer1
    self.nodes_in_layer2=nodes_in_layer2
    self.nodes_in_layer3=nodes_in_layer3


    self.thetas_layer0=np.random.rand(self.inputs_in_layer0.shape[1]+1,self.nodes_in_layer1)
    self.thetas_layer1=np.random.rand(self.nodes_in_layer1 + 1,self.nodes_in_layer2)
    self.thetas_layer2=np.random.rand(self.nodes_in_layer2 + 1,self.nodes_in_layer3)

  def feedforward(self):

    self.Z1=self.thetas_layer0[0]+np.dot(self.inputs_in_layer0,self.thetas_layer0[1:])
    self.layer1=sigmoid(self.Z1)

    self.Z2=self.thetas_layer1[0]+np.dot(self.layer1,self.thetas_layer1[1:])
    self.layer2=sigmoid(self.Z2)

    self.Z3=self.thetas_layer2[0]+np.dot(self.layer2,self.thetas_layer2[1:])
    self.layer3=sigmoid(self.Z3)

    return self.layer3

In [53]:
NN=NeuralNetwork(X,Y)
predicted_output=NN.feedforward()
print("Actual Output:  \n",Y)
print("predicted_output: \n",predicted_output,"\n")

Actual Output:  
 [[0]
 [1]
 [1]
 [0]]
predicted_output: 
 [[0.78782673]
 [0.78475592]
 [0.78446799]
 [0.78782673]] 



In [60]:
NN=NeuralNetwork(X,Y)

predicted_output=NN.feedforward()
print("Actual Output:  \n",Y)
print("predicted_output: \n",predicted_output,"\n")

Actual Output:  
 [[0]
 [1]
 [1]
 [0]]
predicted_output: 
 [[0.91521965]
 [0.9136716 ]
 [0.91397832]
 [0.91521965]] 

